spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.99.100:5432/moduledb
      username: moduledb
      password: password
  jpa:
     hibernate:
       show-sql: false
     properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
     database-plateform: org.hibernate.dialect.PostgreSQL9Dialect
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1