spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.99.100:5432/moduledb
      username: moduledb
      password: password
  jpa:
     hibernate:
       id:
          new_generator_mappings: false
      show-sql: false
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1